"""baseline_schema

Revision ID: 4085bd1d44e4
Revises:
Create Date: 2026-02-07 22:55:53.191906

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4085bd1d44e4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_tokens",
        sa.Column("token_id", sa.String(length=32), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("sensor_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sequence", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("token_id"),
    )
    op.create_index(
        op.f("ix_api_tokens_token_hash"), "api_tokens", ["token_hash"], unique=True
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=True),
        sa.Column("resource", sa.String(length=128), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_log_event_type"), "audit_log", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_timestamp"), "audit_log", ["timestamp"], unique=False
    )
    op.create_table(
        "ingest_jobs",
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("sensor_id", sa.String(length=64), nullable=False),
        sa.Column("batch_id", sa.String(length=64), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_msg", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("job_id"),
        sa.UniqueConstraint("sensor_id", "batch_id", name="uq_ingest_sensor_batch"),
    )
    op.create_index(
        "idx_jobs_status_next",
        "ingest_jobs",
        ["status", "next_attempt_at"],
        unique=False,
    )

    op.create_index(
        op.f("ix_ingest_jobs_received_at"), "ingest_jobs", ["received_at"], unique=False
    )
    op.create_index(
        op.f("ix_ingest_jobs_status"), "ingest_jobs", ["status"], unique=False
    )
    op.create_table(
        "sensors",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("sensor_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("alert_type", sa.String(length=50), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("bssid", sa.String(length=17), nullable=True),
        sa.Column("ssid", sa.String(length=32), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=True),
        sa.Column("reason_codes", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("impact", sa.Float(), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("mitre_attack", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False
    )
    op.create_index(
        op.f("ix_alerts_created_at"), "alerts", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_alerts_sensor_id"), "alerts", ["sensor_id"], unique=False)
    op.create_index(op.f("ix_alerts_severity"), "alerts", ["severity"], unique=False)
    op.create_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    op.create_index(
        "ix_alerts_status_created_at", "alerts", ["status", "created_at"], unique=False
    )
    op.create_table(
        "telemetry",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sensor_id", sa.String(length=64), nullable=True),
        sa.Column("batch_id", sa.String(length=64), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bssid", sa.String(length=17), nullable=True),
        sa.Column("ssid", sa.String(length=32), nullable=True),
        sa.Column("channel", sa.Integer(), nullable=True),
        sa.Column("rssi_dbm", sa.Integer(), nullable=True),
        sa.Column("frequency_mhz", sa.Integer(), nullable=True),
        sa.Column("security", sa.String(length=20), nullable=True),
        sa.Column("capabilities", sa.JSON(), nullable=True),
        sa.Column("rsn_info", sa.JSON(), nullable=True),
        sa.Column("raw_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensors.id"],
        ),
        sa.PrimaryKeyConstraint("timestamp", "id")
        if op.get_bind().dialect.name == "postgresql"
        else sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_telemetry_batch_id"), "telemetry", ["batch_id"], unique=False
    )
    op.create_index(op.f("ix_telemetry_bssid"), "telemetry", ["bssid"], unique=False)
    op.create_index(
        "ix_telemetry_bssid_timestamp",
        "telemetry",
        ["bssid", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_telemetry_sensor_id"), "telemetry", ["sensor_id"], unique=False
    )
    op.create_index(
        op.f("ix_telemetry_timestamp"), "telemetry", ["timestamp"], unique=False
    )
    op.create_index(
        "ix_telemetry_sensor_timestamp",
        "telemetry",
        ["sensor_id", "timestamp"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_telemetry_timestamp"), table_name="telemetry")
    op.drop_index(op.f("ix_telemetry_sensor_id"), table_name="telemetry")
    op.drop_index("ix_telemetry_bssid_timestamp", table_name="telemetry")
    op.drop_index(op.f("ix_telemetry_bssid"), table_name="telemetry")
    op.drop_index(op.f("ix_telemetry_batch_id"), table_name="telemetry")
    op.drop_table("telemetry")
    op.drop_index(op.f("ix_alerts_status"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_severity"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_sensor_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_created_at"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_type"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_table("sensors")
    op.drop_index(op.f("ix_ingest_jobs_status"), table_name="ingest_jobs")
    op.drop_index(op.f("ix_ingest_jobs_received_at"), table_name="ingest_jobs")
    op.drop_index("idx_jobs_status_next", table_name="ingest_jobs")
    op.drop_table("ingest_jobs")
    op.drop_index(op.f("ix_audit_log_timestamp"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_event_type"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_api_tokens_token_hash"), table_name="api_tokens")
    op.drop_table("api_tokens")
    # ### end Alembic commands ###
