#!/bin/bash
# ============================================================
# Sentinel NetLab - Setup Script
# Installs and configures sensor on Debian/Ubuntu systems
# ============================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Configuration - adjust as needed
INSTALL_DIR="/opt/sentinel"
CONFIG_DIR="/etc/sentinel"
LOG_DIR="/var/log/sentinel"
JOURNAL_DIR="/var/lib/sentinel/journal"
REPO_URL="https://github.com/Anduong1200/sentinel-netlab.git"
IFACE="wlan0"  # Default interface

echo "============================================"
echo "  Sentinel NetLab - Setup Script"
echo "============================================"
echo ""

# Check root
if [ "$EUID" -ne 0 ]; then
    log_error "Please run as root (sudo ./setup.sh)"
    exit 1
fi

# ============================================================
# A. Prerequisites (OS & packages)
# ============================================================
log_info "Step A: Installing system packages..."

apt update && apt upgrade -y

apt install -y \
    python3 python3-venv python3-pip \
    build-essential libpcap-dev libffi-dev libssl-dev \
    git wget curl jq \
    iproute2 iw rfkill \
    wireless-tools

log_info "System packages installed."

# ============================================================
# B. Create sentinel user & directories
# ============================================================
log_info "Step B: Creating sentinel user and directories..."

# Create user if not exists
if ! id "sentinel" &>/dev/null; then
    useradd --system --no-create-home --shell /usr/sbin/nologin sentinel
    log_info "Created user 'sentinel'"
else
    log_info "User 'sentinel' already exists"
fi

# Create directories
mkdir -p "$INSTALL_DIR"
mkdir -p "$CONFIG_DIR"
mkdir -p "$LOG_DIR"
mkdir -p "$JOURNAL_DIR"
mkdir -p "$CONFIG_DIR/certs"

chown -R sentinel:sentinel "$INSTALL_DIR" "$LOG_DIR" "$JOURNAL_DIR"
chown -R root:sentinel "$CONFIG_DIR"
chmod 750 "$CONFIG_DIR"

log_info "Directories created."

# ============================================================
# C. Deploy code & create Python venv
# ============================================================
log_info "Step C: Deploying code..."

if [ -d "$INSTALL_DIR/.git" ]; then
    log_info "Repository exists, pulling updates..."
    sudo -u sentinel git -C "$INSTALL_DIR" pull
else
    log_info "Cloning repository..."
    sudo -u sentinel git clone "$REPO_URL" "$INSTALL_DIR"
fi

log_info "Creating Python virtual environment..."
sudo -u sentinel python3 -m venv "$INSTALL_DIR/venv"

log_info "Installing Python dependencies..."
sudo -u sentinel "$INSTALL_DIR/venv/bin/pip" install --upgrade pip
sudo -u sentinel "$INSTALL_DIR/venv/bin/pip" install -r "$INSTALL_DIR/sensor/requirements.txt"

log_info "Code deployed and dependencies installed."

# ============================================================
# D. Configuration files
# ============================================================
log_info "Step D: Creating configuration files..."

# Create config.yaml if not exists
if [ ! -f "$CONFIG_DIR/config.yaml" ]; then
    cat > "$CONFIG_DIR/config.yaml" << 'EOF'
# Sentinel NetLab Sensor Configuration
# Generated by setup.sh - customize as needed

sensor:
  id: "sensor-01"
  interface: "wlan0"

capture:
  method: "scapy"
  channels: [1, 6, 11]
  dwell_ms: 200

buffer:
  max_items: 10000
  storage_path: "/var/lib/sentinel/journal"

transport:
  upload_url: "http://localhost:5000/api/v1/telemetry"
  # auth_token loaded from env file
  timeout_sec: 30

upload:
  batch_size: 200
  interval_sec: 5.0

privacy:
  anonymize_ssid: false

logging:
  level: "INFO"
EOF
    chown root:sentinel "$CONFIG_DIR/config.yaml"
    chmod 640 "$CONFIG_DIR/config.yaml"
    log_info "Created config.yaml"
else
    log_info "config.yaml already exists, skipping"
fi

# Create env file for secrets
if [ ! -f "$CONFIG_DIR/env" ]; then
    cat > "$CONFIG_DIR/env" << 'EOF'
# Sentinel NetLab Environment Variables
# Secrets and sensitive configuration
BEARER_TOKEN=sentinel-dev-2024
# CLIENT_CERT=/etc/sentinel/certs/client.pem
EOF
    chown root:sentinel "$CONFIG_DIR/env"
    chmod 640 "$CONFIG_DIR/env"
    log_info "Created env file"
else
    log_info "env file already exists, skipping"
fi

# ============================================================
# E. Install monitor mode helper script
# ============================================================
log_info "Step E: Installing monitor mode helper..."

cp "$INSTALL_DIR/ops/systemd/sentinel-ensure-monitor-mode" /usr/local/bin/
chmod 755 /usr/local/bin/sentinel-ensure-monitor-mode

log_info "Monitor mode helper installed."

# ============================================================
# F. Install systemd service
# ============================================================
log_info "Step F: Installing systemd service..."

# Install template service
cp "$INSTALL_DIR/ops/systemd/sentinel-sensor@.service" /etc/systemd/system/
cp "$INSTALL_DIR/ops/systemd/sentinel-sensor.service" /etc/systemd/system/

systemctl daemon-reload

log_info "Systemd services installed."

# ============================================================
# G. Log rotation
# ============================================================
log_info "Step G: Configuring log rotation..."

cat > /etc/logrotate.d/sentinel << 'EOF'
/var/log/sentinel/*.log {
    daily
    rotate 14
    compress
    missingok
    notifempty
    create 0640 sentinel sentinel
    postrotate
        systemctl kill -s SIGUSR1 sentinel-sensor.service >/dev/null 2>&1 || true
    endscript
}
EOF

log_info "Log rotation configured."

# ============================================================
# Done
# ============================================================
echo ""
echo "============================================"
echo -e "${GREEN}  Setup Complete!${NC}"
echo "============================================"
echo ""
echo "Next steps:"
echo "  1. Edit /etc/sentinel/config.yaml with your settings"
echo "  2. Update /etc/sentinel/env with secure token"
echo "  3. Enable and start service:"
echo ""
echo "     # For single interface:"
echo "     sudo systemctl enable --now sentinel-sensor.service"
echo ""
echo "     # For template (multiple interfaces):"
echo "     sudo systemctl enable --now sentinel-sensor@wlan0.service"
echo ""
echo "  4. Check status:"
echo "     sudo systemctl status sentinel-sensor.service"
echo "     sudo journalctl -u sentinel-sensor.service -f"
echo ""
echo "  5. Verify monitor mode:"
echo "     iw dev"
echo ""
