#!/usr/bin/env python3
"""Smoke test for the lab environment through the localhost proxy."""

from __future__ import annotations

import secrets
import shutil
import subprocess
import sys
import time
from pathlib import Path

import requests

LAB_ENV_PATH = Path("ops/.env.lab")
LAB_COMPOSE_FILE = Path("ops/docker-compose.lab.yml")
PROXY_BASE_URL = "http://127.0.0.1:8080"
PROXY_HEALTH_URL = f"{PROXY_BASE_URL}/api/v1/health"
PROXY_INGEST_URL = f"{PROXY_BASE_URL}/api/v1/telemetry"
HEALTH_URL = PROXY_HEALTH_URL
TELEMETRY_URL = PROXY_INGEST_URL
MAX_RETRIES = 12
RETRY_DELAY = 5


def compose_command() -> list[str]:
    """Return the supported Compose command for CI/lab smoke runs."""
    docker = shutil.which("docker")
    if docker:
        return [docker, "compose"]

    legacy = shutil.which("docker-compose")
    if legacy:
        return [legacy]

    raise RuntimeError("Docker Compose is required for lab smoke tests.")


def run_cmd(args: list[str], *, check: bool = True) -> None:
    print(f"Running: {' '.join(args)}")
    subprocess.run(args, check=check)


def compose_args(compose: list[str], *extra: str) -> list[str]:
    return compose + [
        "--env-file",
        str(LAB_ENV_PATH),
        "-f",
        str(LAB_COMPOSE_FILE),
        *extra,
    ]


def generate_env_lab() -> None:
    """Generate ops/.env.lab with minimal secrets for CI if it doesn't exist."""
    if LAB_ENV_PATH.exists():
        print(f"✅ {LAB_ENV_PATH} exists")
        return

    print(f"🔧 Generating {LAB_ENV_PATH} for CI...")
    LAB_ENV_PATH.write_text(
        "\n".join(
            [
                "# Auto-generated by lab_smoke.py for CI",
                "ENVIRONMENT=development",
                "POSTGRES_USER=sentinel",
                f"POSTGRES_PASSWORD={secrets.token_hex(16)}",
                "POSTGRES_DB=sentinel",
                f"REDIS_PASSWORD={secrets.token_hex(16)}",
                f"CONTROLLER_SECRET_KEY={secrets.token_hex(32)}",
                f"CONTROLLER_HMAC_SECRET={secrets.token_hex(32)}",
                f"DASHBOARD_API_TOKEN={secrets.token_hex(16)}",
                "DASH_USERNAME=admin",
                f"DASH_PASSWORD={secrets.token_hex(16)}",
                f"SENSOR_AUTH_TOKEN={secrets.token_hex(16)}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"✅ Generated {LAB_ENV_PATH}")


def wait_for_health(url: str) -> None:
    print(f"Waiting for {url}...")
    for _ in range(MAX_RETRIES):
        try:
            response = requests.get(url, timeout=5)
            if response.status_code == 200:
                print("✅ Healthy")
                return
        except requests.exceptions.RequestException:
            pass
        time.sleep(RETRY_DELAY)
    raise RuntimeError("Health check timed out")


def verify_ingest(url: str) -> None:
    print("Verifying telemetry via proxy...")
    headers = {"Authorization": "Bearer admin-token-dev"}
    for _ in range(MAX_RETRIES):
        try:
            response = requests.get(
                url, headers=headers, params={"limit": 1}, timeout=5
            )
            if response.status_code == 200 and len(response.json()) > 0:
                print(f"✅ Telemetry found: {len(response.json())} records")
                return
        except Exception:  # noqa: BLE001,S110
            pass
        time.sleep(RETRY_DELAY)
    raise RuntimeError("No telemetry found after seed")


def main() -> None:
    compose: list[str] | None = None
    try:
        print("=== Lab Smoke Test (Proxy Path) ===")
        compose = compose_command()
        generate_env_lab()

        run_cmd(compose_args(compose, "up", "-d", "--build"))
        wait_for_health(PROXY_HEALTH_URL)

        print("🌱 Seeding Data...")
        run_cmd(compose_args(compose, "run", "--rm", "seed"))
        verify_ingest(PROXY_INGEST_URL)

        print("\n✅ Smoke Test Passed!")
    except KeyboardInterrupt:
        print("\nAborted.")
        sys.exit(1)
    except Exception as exc:  # noqa: BLE001
        print(f"\n❌ Error: {exc}")
        if compose is not None:
            try:
                print("\n=== Compose Logs: controller ===")
                run_cmd(compose_args(compose, "logs", "controller"), check=False)
                print("=== End Logs ===\n")
            except Exception:  # noqa: BLE001,S110
                pass
        sys.exit(1)
    finally:
        if compose is not None:
            print("\n=== Teardown ===")
            run_cmd(compose_args(compose, "down", "-v"), check=False)


if __name__ == "__main__":
    main()
