#!/usr/bin/env python3
"""Smoke test for the lab environment through the localhost proxy."""

from __future__ import annotations

import secrets
import subprocess
import sys
import time
from pathlib import Path

import requests

PROXY_BASE_URL = "http://127.0.0.1:8080"
HEALTH_URL = f"{PROXY_BASE_URL}/api/v1/health"
TELEMETRY_URL = f"{PROXY_BASE_URL}/api/v1/telemetry"
ENV_PATH = Path("ops/.env.lab")
MAX_RETRIES = 12
RETRY_DELAY = 5


def run_cmd(cmd: str) -> None:
    print(f"Running: {cmd}")
    result = subprocess.run(cmd, shell=True, check=False)  # noqa: S602
    if result.returncode != 0:
        print(f"Command failed: {cmd}")
        raise RuntimeError(cmd)


def generate_env_lab() -> None:
    """Generate ops/.env.lab with minimal secrets for CI if it doesn't exist."""
    if ENV_PATH.exists():
        print(f"OK: {ENV_PATH} exists")
        return

    print(f"Generating {ENV_PATH} for CI...")
    env_content = f"""# Auto-generated by lab_smoke.py for CI
ENVIRONMENT=development
POSTGRES_USER=sentinel
POSTGRES_PASSWORD={secrets.token_hex(16)}
POSTGRES_DB=sentinel
REDIS_PASSWORD={secrets.token_hex(16)}
CONTROLLER_SECRET_KEY={secrets.token_hex(32)}
CONTROLLER_HMAC_SECRET={secrets.token_hex(32)}
DASHBOARD_API_TOKEN={secrets.token_hex(16)}
DASH_USERNAME=admin
DASH_PASSWORD={secrets.token_hex(16)}
SENSOR_AUTH_TOKEN={secrets.token_hex(16)}
"""
    ENV_PATH.write_text(env_content, encoding="utf-8")
    print(f"OK: Generated {ENV_PATH}")


def wait_for_health_check(url: str = HEALTH_URL) -> None:
    print(f"Waiting for {url}...")
    for _ in range(MAX_RETRIES):
        try:
            response = requests.get(url, timeout=5)
            if response.status_code == 200:
                print("OK: Healthy")
                return
        except requests.exceptions.RequestException:
            pass
        time.sleep(RETRY_DELAY)
    raise RuntimeError(f"Health check timed out: {url}")


def verify_ingest_via_proxy(url: str = TELEMETRY_URL) -> None:
    print(f"Verifying via proxy: {url}")
    headers = {"Authorization": "Bearer admin-token-dev"}
    for _ in range(MAX_RETRIES):
        try:
            response = requests.get(
                url,
                headers=headers,
                params={"limit": 1},
                timeout=5,
            )
            if response.status_code == 200 and len(response.json()) > 0:
                print(f"OK: Telemetry found: {len(response.json())} records")
                return
        except Exception:  # noqa: BLE001,S110
            pass
        time.sleep(RETRY_DELAY)
    raise RuntimeError(f"No data found after seed: {url}")


def main() -> None:
    try:
        print("=== Lab Smoke Test ===")
        print(f"Test Target: Proxy ({PROXY_BASE_URL})")

        generate_env_lab()
        run_cmd(
            "docker compose --env-file ops/.env.lab -f ops/docker-compose.lab.yml up -d --build"
        )
        wait_for_health_check()

        print("Seeding data...")
        run_cmd(
            "docker compose --env-file ops/.env.lab -f ops/docker-compose.lab.yml run --rm seed"
        )
        verify_ingest_via_proxy()
        print("\nSmoke test passed")
    except KeyboardInterrupt:
        print("\nAborted.")
    except Exception as exc:  # noqa: BLE001
        print(f"\nError: {exc}")
        try:
            print("\n=== Controller Logs ===")
            run_cmd("docker logs sentinel-lab-controller")
            print("=== End Logs ===\n")
        except Exception:  # noqa: BLE001,S110
            pass
        sys.exit(1)
    finally:
        print("\n=== Teardown ===")
        try:
            run_cmd(
                "docker compose --env-file ops/.env.lab -f ops/docker-compose.lab.yml down -v"
            )
        except Exception:  # noqa: BLE001,S110
            pass


if __name__ == "__main__":
    main()
